sonar.projectKey=Vivien-PARSIS-Tasklist-Backend
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server.ts,src/app.ts,src/lib/prisma.ts,*/*.config.ts,**/*.d.ts,src/__tests__/e2e/*.ts,src/__tests__/unit/*.ts,src/routes/*.ts